#!/usr/bin/env python3
import sys
import json
import re

# Phone number prefix database (country code → country/carrier info)
COUNTRY_CODES = {
    "1": {"country": "United States / Canada", "flag": "🇺🇸", "region": "North America"},
    "7": {"country": "Russia / Kazakhstan", "flag": "🇷🇺", "region": "Europe/Asia"},
    "20": {"country": "Egypt", "flag": "🇪🇬", "region": "Africa"},
    "27": {"country": "South Africa", "flag": "🇿🇦", "region": "Africa"},
    "30": {"country": "Greece", "flag": "🇬🇷", "region": "Europe"},
    "31": {"country": "Netherlands", "flag": "🇳🇱", "region": "Europe"},
    "32": {"country": "Belgium", "flag": "🇧🇪", "region": "Europe"},
    "33": {"country": "France", "flag": "🇫🇷", "region": "Europe"},
    "34": {"country": "Spain", "flag": "🇪🇸", "region": "Europe"},
    "36": {"country": "Hungary", "flag": "🇭🇺", "region": "Europe"},
    "39": {"country": "Italy", "flag": "🇮🇹", "region": "Europe"},
    "40": {"country": "Romania", "flag": "🇷🇴", "region": "Europe"},
    "41": {"country": "Switzerland", "flag": "🇨🇭", "region": "Europe"},
    "43": {"country": "Austria", "flag": "🇦🇹", "region": "Europe"},
    "44": {"country": "United Kingdom", "flag": "🇬🇧", "region": "Europe"},
    "45": {"country": "Denmark", "flag": "🇩🇰", "region": "Europe"},
    "46": {"country": "Sweden", "flag": "🇸🇪", "region": "Europe"},
    "47": {"country": "Norway", "flag": "🇳🇴", "region": "Europe"},
    "48": {"country": "Poland", "flag": "🇵🇱", "region": "Europe"},
    "49": {"country": "Germany", "flag": "🇩🇪", "region": "Europe"},
    "51": {"country": "Peru", "flag": "🇵🇪", "region": "South America"},
    "52": {"country": "Mexico", "flag": "🇲🇽", "region": "North America"},
    "53": {"country": "Cuba", "flag": "🇨🇺", "region": "Caribbean"},
    "54": {"country": "Argentina", "flag": "🇦🇷", "region": "South America"},
    "55": {"country": "Brazil", "flag": "🇧🇷", "region": "South America"},
    "56": {"country": "Chile", "flag": "🇨🇱", "region": "South America"},
    "57": {"country": "Colombia", "flag": "🇨🇴", "region": "South America"},
    "58": {"country": "Venezuela", "flag": "🇻🇪", "region": "South America"},
    "60": {"country": "Malaysia", "flag": "🇲🇾", "region": "Asia"},
    "61": {"country": "Australia", "flag": "🇦🇺", "region": "Oceania"},
    "62": {"country": "Indonesia", "flag": "🇮🇩", "region": "Asia"},
    "63": {"country": "Philippines", "flag": "🇵🇭", "region": "Asia"},
    "64": {"country": "New Zealand", "flag": "🇳🇿", "region": "Oceania"},
    "65": {"country": "Singapore", "flag": "🇸🇬", "region": "Asia"},
    "66": {"country": "Thailand", "flag": "🇹🇭", "region": "Asia"},
    "81": {"country": "Japan", "flag": "🇯🇵", "region": "Asia"},
    "82": {"country": "South Korea", "flag": "🇰🇷", "region": "Asia"},
    "84": {"country": "Vietnam", "flag": "🇻🇳", "region": "Asia"},
    "86": {"country": "China", "flag": "🇨🇳", "region": "Asia"},
    "90": {"country": "Turkey", "flag": "🇹🇷", "region": "Europe/Asia"},
    "91": {"country": "India", "flag": "🇮🇳", "region": "Asia"},
    "92": {"country": "Pakistan", "flag": "🇵🇰", "region": "Asia"},
    "93": {"country": "Afghanistan", "flag": "🇦🇫", "region": "Asia"},
    "94": {"country": "Sri Lanka", "flag": "🇱🇰", "region": "Asia"},
    "95": {"country": "Myanmar", "flag": "🇲🇲", "region": "Asia"},
    "98": {"country": "Iran", "flag": "🇮🇷", "region": "Asia"},
    "212": {"country": "Morocco", "flag": "🇲🇦", "region": "Africa"},
    "213": {"country": "Algeria", "flag": "🇩🇿", "region": "Africa"},
    "216": {"country": "Tunisia", "flag": "🇹🇳", "region": "Africa"},
    "218": {"country": "Libya", "flag": "🇱🇾", "region": "Africa"},
    "220": {"country": "Gambia", "flag": "🇬🇲", "region": "Africa"},
    "221": {"country": "Senegal", "flag": "🇸🇳", "region": "Africa"},
    "222": {"country": "Mauritania", "flag": "🇲🇷", "region": "Africa"},
    "223": {"country": "Mali", "flag": "🇲🇱", "region": "Africa"},
    "224": {"country": "Guinea", "flag": "🇬🇳", "region": "Africa"},
    "225": {"country": "Ivory Coast", "flag": "🇨🇮", "region": "Africa"},
    "226": {"country": "Burkina Faso", "flag": "🇧🇫", "region": "Africa"},
    "227": {"country": "Niger", "flag": "🇳🇪", "region": "Africa"},
    "228": {"country": "Togo", "flag": "🇹🇬", "region": "Africa"},
    "229": {"country": "Benin", "flag": "🇧🇯", "region": "Africa"},
    "230": {"country": "Mauritius", "flag": "🇲🇺", "region": "Africa"},
    "231": {"country": "Liberia", "flag": "🇱🇷", "region": "Africa"},
    "232": {"country": "Sierra Leone", "flag": "🇸🇱", "region": "Africa"},
    "233": {"country": "Ghana", "flag": "🇬🇭", "region": "Africa"},
    "234": {"country": "Nigeria", "flag": "🇳🇬", "region": "Africa"},
    "235": {"country": "Chad", "flag": "🇹🇩", "region": "Africa"},
    "236": {"country": "Central African Republic", "flag": "🇨🇫", "region": "Africa"},
    "237": {"country": "Cameroon", "flag": "🇨🇲", "region": "Africa"},
    "238": {"country": "Cape Verde", "flag": "🇨🇻", "region": "Africa"},
    "239": {"country": "São Tomé and Príncipe", "flag": "🇸🇹", "region": "Africa"},
    "240": {"country": "Equatorial Guinea", "flag": "🇬🇶", "region": "Africa"},
    "241": {"country": "Gabon", "flag": "🇬🇦", "region": "Africa"},
    "242": {"country": "Republic of the Congo", "flag": "🇨🇬", "region": "Africa"},
    "243": {"country": "DR Congo", "flag": "🇨🇩", "region": "Africa"},
    "244": {"country": "Angola", "flag": "🇦🇴", "region": "Africa"},
    "245": {"country": "Guinea-Bissau", "flag": "🇬🇼", "region": "Africa"},
    "246": {"country": "British Indian Ocean Territory", "flag": "🇮🇴", "region": "Asia"},
    "247": {"country": "Ascension Island", "flag": "🇸🇭", "region": "Africa"},
    "248": {"country": "Seychelles", "flag": "🇸🇨", "region": "Africa"},
    "249": {"country": "Sudan", "flag": "🇸🇩", "region": "Africa"},
    "250": {"country": "Rwanda", "flag": "🇷🇼", "region": "Africa"},
    "251": {"country": "Ethiopia", "flag": "🇪🇹", "region": "Africa"},
    "252": {"country": "Somalia", "flag": "🇸🇴", "region": "Africa"},
    "253": {"country": "Djibouti", "flag": "🇩🇯", "region": "Africa"},
    "254": {"country": "Kenya", "flag": "🇰🇪", "region": "Africa"},
    "255": {"country": "Tanzania", "flag": "🇹🇿", "region": "Africa"},
    "256": {"country": "Uganda", "flag": "🇺🇬", "region": "Africa"},
    "257": {"country": "Burundi", "flag": "🇧🇮", "region": "Africa"},
    "258": {"country": "Mozambique", "flag": "🇲🇿", "region": "Africa"},
    "260": {"country": "Zambia", "flag": "🇿🇲", "region": "Africa"},
    "261": {"country": "Madagascar", "flag": "🇲🇬", "region": "Africa"},
    "262": {"country": "Reunion / Mayotte", "flag": "🇷🇪", "region": "Africa"},
    "263": {"country": "Zimbabwe", "flag": "🇿🇼", "region": "Africa"},
    "264": {"country": "Namibia", "flag": "🇳🇦", "region": "Africa"},
    "265": {"country": "Malawi", "flag": "🇲🇼", "region": "Africa"},
    "266": {"country": "Lesotho", "flag": "🇱🇸", "region": "Africa"},
    "267": {"country": "Botswana", "flag": "🇧🇼", "region": "Africa"},
    "268": {"country": "Eswatini", "flag": "🇸🇿", "region": "Africa"},
    "269": {"country": "Comoros", "flag": "🇰🇲", "region": "Africa"},
    "290": {"country": "Saint Helena", "flag": "🇸🇭", "region": "Africa"},
    "291": {"country": "Eritrea", "flag": "🇪🇷", "region": "Africa"},
    "297": {"country": "Aruba", "flag": "🇦🇼", "region": "Caribbean"},
    "298": {"country": "Faroe Islands", "flag": "🇫🇴", "region": "Europe"},
    "299": {"country": "Greenland", "flag": "🇬🇱", "region": "North America"},
    "350": {"country": "Gibraltar", "flag": "🇬🇮", "region": "Europe"},
    "351": {"country": "Portugal", "flag": "🇵🇹", "region": "Europe"},
    "352": {"country": "Luxembourg", "flag": "🇱🇺", "region": "Europe"},
    "353": {"country": "Ireland", "flag": "🇮🇪", "region": "Europe"},
    "354": {"country": "Iceland", "flag": "🇮🇸", "region": "Europe"},
    "355": {"country": "Albania", "flag": "🇦🇱", "region": "Europe"},
    "356": {"country": "Malta", "flag": "🇲🇹", "region": "Europe"},
    "357": {"country": "Cyprus", "flag": "🇨🇾", "region": "Europe"},
    "358": {"country": "Finland", "flag": "🇫🇮", "region": "Europe"},
    "359": {"country": "Bulgaria", "flag": "🇧🇬", "region": "Europe"},
    "370": {"country": "Lithuania", "flag": "🇱🇹", "region": "Europe"},
    "371": {"country": "Latvia", "flag": "🇱🇻", "region": "Europe"},
    "372": {"country": "Estonia", "flag": "🇪🇪", "region": "Europe"},
    "373": {"country": "Moldova", "flag": "🇲🇩", "region": "Europe"},
    "374": {"country": "Armenia", "flag": "🇦🇲", "region": "Asia"},
    "375": {"country": "Belarus", "flag": "🇧🇾", "region": "Europe"},
    "376": {"country": "Andorra", "flag": "🇦🇩", "region": "Europe"},
    "377": {"country": "Monaco", "flag": "🇲🇨", "region": "Europe"},
    "378": {"country": "San Marino", "flag": "🇸🇲", "region": "Europe"},
    "380": {"country": "Ukraine", "flag": "🇺🇦", "region": "Europe"},
    "381": {"country": "Serbia", "flag": "🇷🇸", "region": "Europe"},
    "382": {"country": "Montenegro", "flag": "🇲🇪", "region": "Europe"},
    "385": {"country": "Croatia", "flag": "🇭🇷", "region": "Europe"},
    "386": {"country": "Slovenia", "flag": "🇸🇮", "region": "Europe"},
    "387": {"country": "Bosnia and Herzegovina", "flag": "🇧🇦", "region": "Europe"},
    "389": {"country": "North Macedonia", "flag": "🇲🇰", "region": "Europe"},
    "420": {"country": "Czech Republic", "flag": "🇨🇿", "region": "Europe"},
    "421": {"country": "Slovakia", "flag": "🇸🇰", "region": "Europe"},
    "423": {"country": "Liechtenstein", "flag": "🇱🇮", "region": "Europe"},
    "500": {"country": "Falkland Islands", "flag": "🇫🇰", "region": "South America"},
    "501": {"country": "Belize", "flag": "🇧🇿", "region": "Central America"},
    "502": {"country": "Guatemala", "flag": "🇬🇹", "region": "Central America"},
    "503": {"country": "El Salvador", "flag": "🇸🇻", "region": "Central America"},
    "504": {"country": "Honduras", "flag": "🇭🇳", "region": "Central America"},
    "505": {"country": "Nicaragua", "flag": "🇳🇮", "region": "Central America"},
    "506": {"country": "Costa Rica", "flag": "🇨🇷", "region": "Central America"},
    "507": {"country": "Panama", "flag": "🇵🇦", "region": "Central America"},
    "508": {"country": "Saint Pierre and Miquelon", "flag": "🇵🇲", "region": "North America"},
    "509": {"country": "Haiti", "flag": "🇭🇹", "region": "Caribbean"},
    "590": {"country": "Guadeloupe", "flag": "🇬🇵", "region": "Caribbean"},
    "591": {"country": "Bolivia", "flag": "🇧🇴", "region": "South America"},
    "592": {"country": "Guyana", "flag": "🇬🇾", "region": "South America"},
    "593": {"country": "Ecuador", "flag": "🇪🇨", "region": "South America"},
    "594": {"country": "French Guiana", "flag": "🇬🇫", "region": "South America"},
    "595": {"country": "Paraguay", "flag": "🇵🇾", "region": "South America"},
    "596": {"country": "Martinique", "flag": "🇲🇶", "region": "Caribbean"},
    "597": {"country": "Suriname", "flag": "🇸🇷", "region": "South America"},
    "598": {"country": "Uruguay", "flag": "🇺🇾", "region": "South America"},
    "599": {"country": "Netherlands Antilles", "flag": "🇧🇶", "region": "Caribbean"},
    "670": {"country": "East Timor", "flag": "🇹🇱", "region": "Asia"},
    "672": {"country": "Norfolk Island", "flag": "🇳🇫", "region": "Oceania"},
    "673": {"country": "Brunei", "flag": "🇧🇳", "region": "Asia"},
    "674": {"country": "Nauru", "flag": "🇳🇷", "region": "Oceania"},
    "675": {"country": "Papua New Guinea", "flag": "🇵🇬", "region": "Oceania"},
    "676": {"country": "Tonga", "flag": "🇹🇴", "region": "Oceania"},
    "677": {"country": "Solomon Islands", "flag": "🇸🇧", "region": "Oceania"},
    "678": {"country": "Vanuatu", "flag": "🇻🇺", "region": "Oceania"},
    "679": {"country": "Fiji", "flag": "🇫🇯", "region": "Oceania"},
    "680": {"country": "Palau", "flag": "🇵🇼", "region": "Oceania"},
    "681": {"country": "Wallis and Futuna", "flag": "🇼🇫", "region": "Oceania"},
    "682": {"country": "Cook Islands", "flag": "🇨🇰", "region": "Oceania"},
    "683": {"country": "Niue", "flag": "🇳🇺", "region": "Oceania"},
    "685": {"country": "Samoa", "flag": "🇼🇸", "region": "Oceania"},
    "686": {"country": "Kiribati", "flag": "🇰🇮", "region": "Oceania"},
    "687": {"country": "New Caledonia", "flag": "🇳🇨", "region": "Oceania"},
    "688": {"country": "Tuvalu", "flag": "🇹🇻", "region": "Oceania"},
    "689": {"country": "French Polynesia", "flag": "🇵🇫", "region": "Oceania"},
    "690": {"country": "Tokelau", "flag": "🇹🇰", "region": "Oceania"},
    "691": {"country": "Micronesia", "flag": "🇫🇲", "region": "Oceania"},
    "692": {"country": "Marshall Islands", "flag": "🇲🇭", "region": "Oceania"},
    "850": {"country": "North Korea", "flag": "🇰🇵", "region": "Asia"},
    "852": {"country": "Hong Kong", "flag": "🇭🇰", "region": "Asia"},
    "853": {"country": "Macau", "flag": "🇲🇴", "region": "Asia"},
    "855": {"country": "Cambodia", "flag": "🇰🇭", "region": "Asia"},
    "856": {"country": "Laos", "flag": "🇱🇦", "region": "Asia"},
    "880": {"country": "Bangladesh", "flag": "🇧🇩", "region": "Asia"},
    "886": {"country": "Taiwan", "flag": "🇹🇼", "region": "Asia"},
    "960": {"country": "Maldives", "flag": "🇲🇻", "region": "Asia"},
    "961": {"country": "Lebanon", "flag": "🇱🇧", "region": "Asia"},
    "962": {"country": "Jordan", "flag": "🇯🇴", "region": "Asia"},
    "963": {"country": "Syria", "flag": "🇸🇾", "region": "Asia"},
    "964": {"country": "Iraq", "flag": "🇮🇶", "region": "Asia"},
    "965": {"country": "Kuwait", "flag": "🇰🇼", "region": "Asia"},
    "966": {"country": "Saudi Arabia", "flag": "🇸🇦", "region": "Asia"},
    "967": {"country": "Yemen", "flag": "🇾🇪", "region": "Asia"},
    "968": {"country": "Oman", "flag": "🇴🇲", "region": "Asia"},
    "970": {"country": "Palestine", "flag": "🇵🇸", "region": "Asia"},
    "971": {"country": "UAE", "flag": "🇦🇪", "region": "Asia"},
    "972": {"country": "Israel", "flag": "🇮🇱", "region": "Asia"},
    "973": {"country": "Bahrain", "flag": "🇧🇭", "region": "Asia"},
    "974": {"country": "Qatar", "flag": "🇶🇦", "region": "Asia"},
    "975": {"country": "Bhutan", "flag": "🇧🇹", "region": "Asia"},
    "976": {"country": "Mongolia", "flag": "🇲🇳", "region": "Asia"},
    "977": {"country": "Nepal", "flag": "🇳🇵", "region": "Asia"},
    "992": {"country": "Tajikistan", "flag": "🇹🇯", "region": "Asia"},
    "993": {"country": "Turkmenistan", "flag": "🇹🇲", "region": "Asia"},
    "994": {"country": "Azerbaijan", "flag": "🇦🇿", "region": "Asia"},
    "995": {"country": "Georgia", "flag": "🇬🇪", "region": "Asia"},
    "996": {"country": "Kyrgyzstan", "flag": "🇰🇬", "region": "Asia"},
    "998": {"country": "Uzbekistan", "flag": "🇺🇿", "region": "Asia"},
}

# Pakistan carrier prefixes (example for detailed carrier detection)
PAKISTAN_CARRIERS = {
    # Jazz (formerly Mobilink + Warid merged)
    "300": "Jazz", "301": "Jazz", "302": "Jazz", "303": "Jazz",
    "304": "Jazz", "305": "Jazz", "306": "Jazz", "307": "Jazz",
    "308": "Jazz", "309": "Jazz",
    "310": "Jazz", "311": "Jazz", "312": "Jazz", "313": "Jazz",
    "314": "Jazz", "315": "Jazz", "316": "Jazz", "317": "Jazz",
    "318": "Jazz", "319": "Jazz",
    "320": "Jazz", "321": "Jazz",
    "330": "Jazz", "331": "Jazz", "332": "Jazz", "333": "Jazz",
    "334": "Jazz", "335": "Jazz", "336": "Jazz", "337": "Jazz",
    "338": "Jazz", "339": "Jazz",
    "340": "Jazz", "341": "Jazz", "342": "Jazz", "343": "Jazz",
    "344": "Jazz", "345": "Jazz", "346": "Jazz", "347": "Jazz",
    "348": "Jazz", "349": "Jazz",
    # Telenor
    "350": "Telenor", "351": "Telenor", "352": "Telenor", "353": "Telenor",
    "354": "Telenor", "355": "Telenor", "356": "Telenor", "357": "Telenor",
    "358": "Telenor", "359": "Telenor",
    "360": "Telenor", "361": "Telenor", "362": "Telenor", "363": "Telenor",
    "364": "Telenor", "365": "Telenor", "366": "Telenor",
    # Ufone
    "333": "Ufone", "334": "Ufone",
    "370": "Ufone", "371": "Ufone", "372": "Ufone", "373": "Ufone",
    "374": "Ufone", "375": "Ufone", "376": "Ufone",
    # Zong
    "310": "Zong", "311": "Zong", "312": "Zong", "313": "Zong",
    "314": "Zong", "315": "Zong", "316": "Zong", "317": "Zong",
    "318": "Zong", "319": "Zong",
    "380": "Zong", "381": "Zong", "382": "Zong", "383": "Zong",
    "384": "Zong", "385": "Zong", "386": "Zong",
}

def lookup(number: str) -> dict:
    # Clean the number
    number = re.sub(r'[\s\-\(\)\+]', '', number)
    if not number.isdigit():
        return {"error": "Invalid phone number format"}

    # Try matching country code (longest prefix first: 3, 2, 1 digits)
    country_info = None
    country_code = None
    for length in [3, 2, 1]:
        prefix = number[:length]
        if prefix in COUNTRY_CODES:
            country_info = COUNTRY_CODES[prefix]
            country_code = prefix
            break

    if not country_info:
        return {"error": "Unknown country code"}

    national_number = number[len(country_code):]
    line_type = "Mobile" if len(national_number) >= 9 else "Landline/Unknown"

    carrier = "Unknown"
    if country_code == "92" and len(national_number) >= 10:
        prefix3 = national_number[:3]
        carrier = PAKISTAN_CARRIERS.get(prefix3, "Unknown carrier")

    result = {
        "number": f"+{number}",
        "country_code": f"+{country_code}",
        "country": country_info["country"],
        "flag": country_info["flag"],
        "region": country_info["region"],
        "national_number": national_number,
        "line_type": line_type,
        "carrier": carrier,
        "length": len(national_number),
        "valid": len(national_number) >= 6 and len(national_number) <= 13
    }
    return result

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(json.dumps({"error": "No number provided"}))
        sys.exit(1)
    number = sys.argv[1]
    print(json.dumps(lookup(number)))
